//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int Id { get; set; }
        public int Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Street { get; set; }
        public Nullable<int> Build { get; set; }
        public Nullable<int> Flat { get; set; }
        public string Text { get; set; }
    }
}
