//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTesting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTDBEntities : DbContext
    {
        public MTDBEntities()
            : base("name=MTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<OgContact> OgContact { get; set; }
        public virtual DbSet<OgLocation> OgLocation { get; set; }
        public virtual DbSet<OgNotice> OgNotice { get; set; }
        public virtual DbSet<Paragraph> Paragraph { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<PersonBalance> PersonBalance { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogType> LogType { get; set; }
    }
}
