//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Adress { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> FeedBack { get; set; }
        public Nullable<int> Avatar { get; set; }
        public string AboutMe { get; set; }
    }
}
