//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBalance
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Balance { get; set; }
        public System.DateTime DateOfRegBalance { get; set; }
    }
}
